# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_problems_problem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='my_problems',
        ),
        migrations.AddField(
            model_name='problems',
            name='problem_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.TextField(default='0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_score',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_submissions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problems',
            name='problem_id',
            field=models.TextField(default='0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
