# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20160116_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='problem_author',
        ),
    ]
