# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_problems_problem_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('an_id', models.TextField(default='0', editable=False, primary_key=True, serialize=False)),
                ('an_title', models.CharField(max_length=28)),
                ('an_des', models.TextField()),
                ('an_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
