# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='an_id',
            field=models.TextField(default='0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problems',
            name='problem_id',
            field=models.TextField(default='0', editable=False, primary_key=True, serialize=False),
        ),
    ]
