# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20160121_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submit_id', models.TextField(primary_key=True, serialize=False)),
                ('submit_user', models.TextField()),
                ('submit_source', models.TextField()),
                ('submit_output', models.TextField()),
                ('submit_verdict', models.TextField()),
                ('submit_score', models.TextField()),
                ('submit_lang', models.TextField()),
                ('submit_pid', models.TextField()),
                ('submit_time', models.DateTimeField()),
            ],
        ),
    ]
