# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
