# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20160122_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('r_id', models.TextField(primary_key=True, serialize=False)),
                ('user', models.TextField()),
                ('problemId', models.TextField()),
                ('attempt', models.TextField()),
            ],
        ),
    ]
