# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='an_id',
            field=models.AutoField(default='0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problems',
            name='problem_id',
            field=models.AutoField(default='0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restrictions',
            name='r_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
