# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20160128_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
