# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20160129_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='an_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='an_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
