# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20160129_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='submit_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
