# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_submissions_submit_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restrictions',
            old_name='user',
            new_name='userid',
        ),
    ]
