# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20160131_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictions',
            name='attempt',
            field=models.IntegerField(),
        ),
    ]
