# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20160131_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaderBoard',
            fields=[
                ('lb_user', models.TextField(primary_key=True, serialize=False)),
                ('lb_score', models.IntegerField(default=0)),
            ],
        ),
    ]
