# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictions',
            name='allow',
            field=models.TextField(default='true'),
        ),
    ]
