# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 07:29
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20160131_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
