# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20160415_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='submit_etime',
            field=models.TextField(default=0),
        ),
    ]
