# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20160415_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='current_etime',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='problems',
            name='expected_timelimit',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submit_etime',
            field=models.FloatField(default=0),
        ),
    ]
