# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20160415_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='expected_timelimit',
            field=models.TextField(default=5),
        ),
    ]
