# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20160415_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('points_id', models.AutoField(primary_key=True, serialize=False)),
                ('points_user', models.TextField()),
                ('points_list', models.TextField()),
            ],
        ),
    ]
